spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: test
    password: 1234

  ## Hibernate
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true